name: "TNLWaypoints"
main: "net.nonswag.tnl.waypoints.Waypoints"
version: "2.0.0"
api-version: "1.19"
website: "https://www.thenextlvl.net"
depend: ["TNLListener"]
softdepend: ["TNLWorlds"]
author: "NonSwag"